//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.18
//
package com.myapp.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;
import android.view.MotionEvent;
import android.widget.ImageView;
import android.widget.TextView;

import com.easypay.mobilehelper.auth.IdentityManager;
import com.easypay.mobilehelper.auth.StartupAuthErrorDetails;
import com.easypay.mobilehelper.auth.StartupAuthResult;
import com.easypay.mobilehelper.auth.StartupAuthResultHandler;
import com.easypay.mobile.AWSMobileClient;
import com.myapp.R;

/**
 * Splash Activity is the start-up activity that appears until a delay is expired
 * or the user taps the screen.  When the splash activity starts, various app
 * initialization operations are performed.
 */
public class SplashActivity extends Activity {

    private static final String LOG_TAG = SplashActivity.class.getSimpleName();
    private TextView splashText;
    SharedPreferences preferences;
    public static final String MyPREFERENCES = "MyPrefs" ;
    ImageView statusImage;

    private final StartupAuthResultHandler authResultHandler = new StartupAuthResultHandler() {
        @Override
        public void onComplete(final StartupAuthResult authResult) {
            if (authResult.isUserAnonymous()) {
                Log.d(LOG_TAG, "Continuing with unauthenticated (guest) identity.");
            } else {
                final StartupAuthErrorDetails errors = authResult.getErrorDetails();
                Log.e(LOG_TAG, "No Identity could be obtained. Continuing with no identity.",
                    errors.getUnauthenticatedErrorException());
            }
            goMain(SplashActivity.this);
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Log.d(LOG_TAG, "onCreate");

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        statusImage = findViewById(R.id.statusImage);
        preferences = getSharedPreferences(MyPREFERENCES, Context.MODE_PRIVATE);
        splashText = findViewById(R.id.splashText);
        String user = preferences.getString("user",null);
        if (user == null) {
            statusImage.setBackgroundResource(R.drawable.enoll);
        } else {
            statusImage.setBackgroundResource(R.drawable.auth);
        }


        AWSMobileClient.initializeMobileClientIfNecessary(getApplicationContext());
        final IdentityManager identityManager = AWSMobileClient.defaultMobileClient().getIdentityManager();

        identityManager.doStartupAuth(this, authResultHandler, 2000);

    }

    /** Go to the main activity. */
    private void goMain(final Activity callingActivity) {


        callingActivity.startActivity(new Intent(callingActivity,  VideoAuthActivity.class)
                .setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));
        callingActivity.finish();
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        // Touch event bypasses waiting for the splash timeout to expire.
        AWSMobileClient.defaultMobileClient()
            .getIdentityManager()
            .expireSignInTimeout();
        return true;
    }
}
